import { StyleSheet, View, Dimensions } from 'react-native';

const { width: screenWidth, height: screenHeight } = Dimensions.get('window');

export const loginstyle = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#E0F7FA',
    paddingHorizontal: 16,
    paddingVertical: 20,
    justifyContent: 'space-between',
  },
  logoContainer: {
    alignItems: 'center',
    marginTop: 50,
    marginBottom: 10,
  },
  logo: {
    width: 120,
    height: 72,
  },
  cardContainer: {
    backgroundColor: '#F0F4C3',
    borderRadius: 16,
    padding: 20,
    width: '100%',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    flex: 1,
    maxHeight: '75%',
  },
  welcomeContainer: {
    marginTop: 5,
    marginBottom: 20,
    alignItems: 'center',
  },
  welcomeText: {
    fontSize: 26,
    fontWeight: '700',
    color: '#303481',
    textAlign: 'center',
    lineHeight: 32,
  },
  subtitleText: {
    fontSize: 14,
    color: '#666666',
    textAlign: 'center',
    marginBottom: 16,
    marginTop: 8,
  },
  form: {
    width: '100%',
    flex: 1,
  },
  phoneInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    paddingHorizontal: 3,
  },
  countryCode: {
    fontSize: 15,
    fontWeight: '600',
    color: '#303481',
    marginRight: 8,
    backgroundColor: '#fff',
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#303481',
  },
  inputWrapper: {
    flex: 1,
  },
  input: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 14,
    fontSize: 16,
    color: '#303481',
    borderWidth: 1,
    borderColor: '#303481',
    letterSpacing: 1,
  },
  errorText: {
    color: '#dc3545',
    fontSize: 12,
    marginTop: 4,
    textAlign: 'center',
    marginBottom: 8,
    backgroundColor: '#ffe6e6',
    padding: 8,
    borderRadius: 8,
    marginHorizontal: 8,
    fontWeight: '500',
  },
  phoneText: {
    fontSize: 13,
    color: '#303481',
    fontWeight: '600',
  },
  keypadContainer: {
    flex: 1,
    marginTop: 16,
    marginBottom: 10,
    paddingHorizontal: 6,
    justifyContent: 'center',
  },
  keypadRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  numericButton: {
    backgroundColor: '#303481',
    width: '30%',
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 16,
    elevation: 2,
    minHeight: 50,
    maxHeight: 65,
  },
  numericButtonText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '600',
  },
  loginButton: {
    backgroundColor: '#28a745',
  },
  loginButtonText: {
    fontSize: 22,
    color: '#FFFFFF',
  },
  biometricContainer: {
    width: '100%',
    marginBottom: 16,
    gap: 6,
  },
  biometricButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#303481',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginBottom: 6,
    minHeight: 36,
  },
  biometricIcon: {
    color: '#FFFFFF',
    marginRight: 6,
  },
  biometricButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  // iOS-specific biometric button style
  iosBiometricButton: {
    backgroundColor: '#007AFF', // iOS blue
    borderRadius: 12,
    elevation: 0,
    shadowColor: '#007AFF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
    minHeight: 36,
  },
  // Android-specific styles
  androidBiometricButton: {
    backgroundColor: '#4CAF50', // Material green
    borderRadius: 8,
    elevation: 4,
    paddingVertical: 8,
    paddingHorizontal: 16,
    minHeight: 36,
  },
  // Biometric hint text
  biometricHintText: {
    fontSize: 12,
    color: '#666666',
    textAlign: 'center',
    marginTop: 4,
    fontStyle: 'italic',
  },
  // Auto authentication container for iOS
  autoAuthContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  autoAuthText: {
    fontSize: 16,
    color: '#303481',
    textAlign: 'center',
    marginTop: 12,
    fontWeight: '500',
  },
  clearBiometricButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FEE2E2',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#FCA5A5',
    minHeight: 32,
  },
  clearBiometricButtonText: {
    color: '#EF4444',
    fontSize: 12,
    fontWeight: '500',
    marginLeft: 4,
  },
});

export const blockstyle = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    backgroundColor: "#E0F7FA",
  },
  card: {
    backgroundColor: "#F0F4C3",
    padding: 28,
    borderRadius: 16,
    width: '95%',
    maxWidth: 420,
    alignItems: 'center',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 5,
  },
  noteText: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 20,
    textAlign: 'center',
  },
  messageText: {
    fontSize: 18,
    textAlign: 'center',
    marginBottom: 36,
    color: "#444",
    lineHeight: 26,
    paddingHorizontal: 10,
  },
  button: {
    height: 54,
    backgroundColor: "#3467eb",
    justifyContent: "center",
    alignItems: "center", 
    borderRadius: 27,
    width: 160,
    shadowColor: "#3467eb",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 15,
    elevation: 5,
  },
  buttonText: {
    color: "#fff", 
    fontSize: 18,
    fontWeight: "bold",
  },
});

export const pinstyle = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#E0F7FA',
    paddingHorizontal: 16,
    paddingTop: 40,
    paddingBottom: 20,
    justifyContent: 'center',
  },
  cardContainer: {
    backgroundColor: '#F0F4C3',
    borderRadius: 16,
    padding: 20,
    width: '100%',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    flex: 1,
    maxHeight: '90%',
    marginTop: 20,
  },
  headerContainer: {
    alignItems: 'center',
    marginBottom: 20,
  },
  headerText: {
    fontSize: 26,
    fontWeight: '700',
    color: '#303481',
    textAlign: 'center',
    lineHeight: 32,
  },
  subtitleText: {
    fontSize: 14,
    color: '#666666',
    textAlign: 'center',
    marginTop: 8,
  },
  phoneContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    gap: 12,
    flexWrap: 'wrap',
  },
  phoneText: {
    fontSize: 15,
    color: '#303481',
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  backButton: {
    backgroundColor: '#fff',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#303481',
    elevation: 2,
  },
  backButtonText: {
    color: '#303481',
    fontSize: 12,
    fontWeight: '600',
  },
  pinContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 30,
    paddingHorizontal: 5,
    gap: 8,
  },
  pinInput: {
    width: 50,
    height: 50,
    borderWidth: 2,
    borderColor: '#303481',
    borderRadius: 12,
    fontSize: 24,
    textAlign: 'center',
    backgroundColor: '#FFFFFF',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    fontWeight: '600',
    color: '#303481',
  },
  keypadContainer: {
    flex: 1,
    paddingHorizontal: 6,
    justifyContent: 'center',
    marginBottom: 10,
  },
  keypadRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  keypadButton: {
    backgroundColor: '#303481',
    width: '30%',
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 16,
    elevation: 2,
    minHeight: 45,
    maxHeight: 55,
  },
  keypadButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '600',
  },
  biometricContainer: {
    width: '100%',
    marginBottom: 16,
    gap: 6,
    paddingHorizontal: 20,
  },
  biometricButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#303481',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginBottom: 6,
    minHeight: 36,
  },
  biometricIcon: {
    color: '#FFFFFF',
    marginRight: 6,
  },
  biometricButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  clearBiometricButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FEE2E2',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#FCA5A5',
    minHeight: 32,
  },
  clearBiometricButtonText: {
    color: '#EF4444',
    fontSize: 12,
    fontWeight: '500',
    marginLeft: 4,
  },
});

// Add a default export component
export default function MobileStyles() {
  return <View />;
}
